set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_VERSION "Generic")

set(CMAKE_SYSTEM "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_VERSION}")

set(TRIPLE x86_64-elf)

set(CMAKE_C_COMPILER x86_64-elf-gcc)
set(CMAKE_C_COMPILER_TARGET ${TRIPLE})
set(CMAKE_CXX_COMPILER x86_64-elf-g++)
set(CMAKE_CXX_COMPILER_TARGET ${TRIPLE})

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -nostdlib")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)